os: linux

language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

env:
  - JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64

install:
  - sudo add-apt-repository -y ppa:openjdk-r/ppa
  - sudo apt-get -qq update
  - sudo apt-get install -y openjdk-8-jdk --no-install-recommends

script:
  - bin/check-legal
  - bin/test && coveralls
  - bin/check-install
